### ISSUE TITLE
DateRangePicker: selecting date less than startDate causes startDate to be cleared 

### ISSUE THREAD

**Issue by CatsOnFilm** [hernansartorio/react-nice-dates#8]
With the default configuration of DateRangePicker, if you select a date, then select an end date that is earlier, the startDate is cleared. From that point onward, you can select ranges spanning backwards in time (as is probably the expected behaviour). 
A related quirk (which may be the desired behaviour), is that clicking the same date over and over causes the date to swap (clear startDate and set endDate, and vice versa). Though this does make it impossible to set same-day intervals with the default configuration.

**Comment by hernansartorio** [comment]
Thanks for pointing that out. The first thing you mention is expected behavior, but the second one isn't.

When you select a start date and go to select an end date, the start date should be disabled. It was like this but I accidentally undid it with a recent change, will update it and add tests for it.

About same-day intervals selection, I will add an option to allow it.

**Comment by e-power** [comment]
Hey, i also need to be able to select the same Date twice for a single-day selection. Would be very nice if you could add that soon. 

Greetings
